version: '2'
services:
  sso:
    container_name: $SSO_DOCKER_CONTAINER
    image: $SSO_DOCKER_IMAGE
    build:
      context: $SSO_DOCKER_CONTEXT
    hostname: sso
    ports:
      - 8000:8000
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup 
    privileged: true
  consul:
    container_name: consul
    image: progrium/consul
    command: -server -bootstrap 
    hostname: consul 
    ports:
      - 8001:8500
  statsd:
    container_name: statsd
    image: hopsoft/graphite-statsd
    hostname: statsd 
    ports:
      - 8002:80
    expose:
      - 53/udp
      - 2003
      - 2004
      - 2023
      - 2024
      - '8125/udp'
      - 8126
  redis:
    container_name: redis
    image: redis 
    hostname: redis 
    ports:
      - 8003:6379
  ldap:
    container_name: ldap
    image: osixia/openldap  
    hostname: ldap 
    command: --loglevel debug
    environment:
      LDAP_ORGANISATION:  "TEST"
      LDAP_DOMAIN: "example.com"
      LDAP_BASE_DN:  "ou=admin,dc=example,dc=com"
      LDAP_ADMIN_PASSWORD: "password" 
      LDAP_CONFIG_PASSWORD:  "password" 
    ports:
      - 8004:389
      - 636
  ldapgui:
    container_name: ldapgui
    image: osixia/phpldapadmin
    hostname: ldapigui 
    ports:
      - 8005:443
    depends_on:
      - ldap
    volumes:
      - ./ldap/default.startup.yaml:/container/environment/01-miracl/env.yaml 
  syslog:
    container_name: syslog
    image: balabit/syslog-ng
    hostname: syslog
    ports:
      - "514:514/udp"
    volumes:
      - ./syslog/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
  sp:
    container_name: sp
    build:
      context: ./sp
    hostname: sp
    ports:
      - 8080:80
    environment:
      SP_BASEURL: "http://127.0.0.1:8080"
      SP_ENTITYID: "http://127.0.0.1:8080"
      SP_CERT: "$SSO_DOCKER_SP_CERT"
      SP_KEY: "$SSO_DOCKER_SP_KEY"
      IDP_BASEURL: "http://127.0.0.1:8000"
      IDP_ENTITYID: "http://127.0.0.1:8000"
      IDP_CERT: "$SSO_DOCKER_IDP_CERT"
